### ISSUE TITLE
General Announcements

### ISSUE THREAD

**Issue by jordanpapaleo** [CodeTahoe/CT100#1]
Leave comments here for everyone watching this repo

**Comment by jordanpapaleo** [comment]
To All:

Class updates will occur in the Changelog.md.  Take a look and I will explain why we are doing that tonight.  Ill explain these issues too 

- Jordan

**Comment by jordanpapaleo** [comment]
I added a cheat sheet for terminal commands to the [Setup Doc](https://github.com/CodeTahoe/CT100/blob/master/courses/Setting%20up%20your%20dev%20environment.md) and a cheat sheet for git to [Version Control Doc](https://github.com/CodeTahoe/CT100/blob/master/courses/version_control.md)

**Comment by Dylan-Eckert** [comment]
I have been messing around in Github and I can't seem to find the classmates anywhere without trying to search up their profile names. Do we have a sign-up sheet of sorts?

**Comment by jordanpapaleo** [comment]
You can just fork Tim's or even fork this repo.  We will talk about a class list tonight

**Comment by theaaronmartin** [comment]
I found them on the forked page. Go to the main CT100 page, clicked on
fork, and there will be everyone who forked it.

**Comment by TimOlesnavage** [comment]
my screen is cracked - what do i do?

**Comment by lhurt51** [comment]
The version control doc link is broken for me. Can you please fix.

**Comment by jordanpapaleo** [comment]
Someone left a charger at snc. I'll have it at elevate blue tomorrow.

**Comment by theaaronmartin** [comment]
I found a mistake in the html_2.md lesson, where you accidentally mixed up div and span. The titles and examples are correct, but the definitions are mixed up.

**Comment by jordanpapaleo** [comment]
Fixed error in html_2.  Thanks Aaron.

**Comment by jordanpapaleo** [comment]
TODO:  Take last nights lab and copy the code into a new file.  Replace all of the container tags with divs.  How easy is it to read?  Think about why we use semantics in our code.

**Comment by jordanpapaleo** [comment]
So we just finished HTML.  You guys did great and I am quite proud of the progress you have made.  Each class you guys complete assignments faster.  Your speed is why I am bringing this up; I think you can handle it.  

I would like you guys to start thinking about building a page about you.  I think it is really important to have something that you walk away from this class with other than versions of a weird CodeTahoe site.

First Task: 
- Figure out what pages do you want on your website? Landing, Home, About, Contact, *
- Find the content you want for your website.  Content is a killer for any project.  I have seen many sites fizzle out because people cannot produce content.
- Start browsing the web and look for sites that you like, or parts of a site that you like.
    - Also find things that you don't like.  Why didn't you like it?
    - Figure out your web style ;)

This assignment is not one that we will be actively working on in class but it will be a great place for you to experiment and reinforce you skills.  Having said that we can always talk about whatever questions you have during our lab time.

**Comment by jordanpapaleo** [comment]
HOMEWORK:

Before next class find an image for each of the 4 seasons.  Save those images and bring them to class on your computer.

**Comment by jordanpapaleo** [comment]
Hey Everyone - 

I just want to remind the class that Github is intended for class use; it is not just an open communication platform.  Think of it as things you would discuss for working on a project.  I will add a section to the README.md file about this.  If you need to communicate for non class work topics please use email or something else.

Thanks,

Jordan

**Comment by jordanpapaleo** [comment]
JS lessons added.  Check the latest content in the change log.  See everyone tonight

**Comment by jordanpapaleo** [comment]
Updated the changelog and added the lesson plan for tonight

**Comment by Zenprechaun** [comment]
Had doctor's appointment in sac.   On 80.  Half hour late.  


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by jordanpapaleo** [comment]
I finished simon last night so we are good to go for tonight.  But the big question is what do we do tomorrow night.  Please think about it and I will teach you/demonstrate whatever you are interested in

**Comment by Zenprechaun** [comment]
Maybe interact with a database, like with a registration form?

 

Thank you and Cheers,

Mike McDermott, CEO

310-956-2936

 

CONFIDENTIAL NOTICE: All information, data and attachments contained in this message are confidential and are the property of GIVFTiT, Inc. If you are not the intended recipient and have received this email in error delete it immediately and destroy all copies. Any redistribution, communication or actions taken on information contained in this message is strictly prohibited.

**Comment by jordanpapaleo** [comment]
How about something in a language we have worked with ;)

**Comment by jordanpapaleo** [comment]
https://dl.dropboxusercontent.com/u/18759926/simon-game/index.html

**Comment by Zenprechaun** [comment]
Can we get the special promo code from you for the immersion?

 

Thank you and Cheers,

Mike McDermott, CEO

310-956-2936

 

CONFIDENTIAL NOTICE: All information, data and attachments contained in this message are confidential and are the property of GIVFTiT, Inc. If you are not the intended recipient and have received this email in error delete it immediately and destroy all copies. Any redistribution, communication or actions taken on information contained in this message is strictly prohibited.

**Comment by jordanpapaleo** [comment]
Yes. Ill tell you tonight.  Thanks for the reminder :)

**Comment by MarkusBrun** [comment]
So what was the promo code? I think I missed when you said it

**Comment by theaaronmartin** [comment]
firstclass

**Comment by jordanpapaleo** [comment]
Last announcement:

You guys were awesome.  I have always said the best way to learn is to teach.  I learned so much from you guys.  This class affirmed my desire to teach.  Thank you inaugural class of CodeTahoe.  I have one request if you have time.  As I am new to the professional world of teaching I would be so thankful for any sort of recommendation you could put on linkedin.  Your reviews will be super helpful for potential students of CodeTahoe.  

Thanks again everyone,

Jordan

[LinkedIn](https://www.linkedin.com/in/jordanpapaleo)

**Comment by MarkusBrun** [comment]
Hey Jordan, I was trying to leave you a recommendation but I couldn't figure out how to, do I have to add you as a connection for access to give you a recommendation?

**Comment by jordanpapaleo** [comment]
Thanks!  Do you have a linked in account?  You would make a recommendation for me at CodeTahoe. You should add CodeTahoe to your profile as a school. 

Sent from my iPhone

On May 12, 2016, at 3:03 PM, MarkusBrun <notifications@github.com> wrote:

Hey Jordan, I was trying to leave you a recommendation but I couldn't figure out how to, do I have to add you as a connection for access to give you a recommendation?

**Comment by blazehalderman** [comment]
Hi Jordan,

I accidentally made two payments to you Code Tahoe for the Immersive.
Please cancel either one so I don't get charged twice. I look forward to
the first day. I got rid of the mothership for a mac so am super excited to
use it for coding :)

Thanks,
Blaze

On Thu, May 12, 2016 at 4:09 PM, Jordan Papaleo <notifications@github.com>
wrote:

> Thanks! Do you have a linked in account? You would make a recommendation
> for me at CodeTahoe. You should add CodeTahoe to your profile as a school.
>
> Sent from my iPhone
>
> On May 12, 2016, at 3:03 PM, MarkusBrun <notifications@github.com> wrote:
>
> Hey Jordan, I was trying to leave you a recommendation but I couldn't
> figure out how to, do I have to add you as a connection for access to give
> you a recommendation?
>
> —
> You are receiving this because you authored the thread.
>
> Reply to this email directly or view it on GitHub
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeTahoe/CT100/issues/1#issuecomment-218911240>
>



-- 
Blaze
