### ISSUE TITLE
CSS #3 - bootstrap expercise

### ISSUE THREAD

**Issue by Zenprechaun** [CodeTahoe/CT100#10]
So is part of the exercise to have to figure out that the path has to be changed or did I download a different 3.3.6 bootstrap file?

I changed the path in the code to find the bootstrap.min.css file in;
libs\bootstrap-3.3.6-dist\docs\dist\css

**Comment by jordanpapaleo** [comment]
What I did was just an example of it being used. 

Sent from my iPhone

On Apr 14, 2016, at 10:25 PM, Michael McDermott <notifications@github.com> wrote:

So is part of the exercise to have to figure out that the path has to be changed or did I download a different 3.3.6 bootstrap file?

I changed the path in the code to find the bootstrap.min.css file in;
libs\bootstrap-3.3.6-dist\docs\dist\css
