### ISSUE TITLE
To: High School Guys

### ISSUE THREAD

**Issue by jordanpapaleo** [CodeTahoe/CT100#13]
When would you be available to start the summer immersive?  I need dates please.

**Comment by MarkusBrun** [comment]
My school gets out June 16th, If I talk to my counselors I could probably figure out a way to end earlier if I bust out my school work before school ends. Are you thinking of pushing back the bootcamp a couple of days?

**Comment by lhurt51** [comment]
I can start June 15

**Comment by jordanpapaleo** [comment]
Summer immersive starts June 14

**Comment by MarkusBrun** [comment]
I can for sure do that! Thanks for adjusting the dates

**Comment by blazehalderman** [comment]
Hi,

I'll let you know if I can do it or not by next week. Still figuring things
out at the moment. Thanks for adjusting the dates!

Blaze
