### ISSUE TITLE
What is the terminal again

### ISSUE THREAD

**Issue by jordanpapaleo** [CodeTahoe/CT100#3]

**Comment by TimOlesnavage** [comment]
it's the matrix. eat both pills.

**Comment by jordanpapaleo** [comment]
Yeah i dont know either

**Comment by drdelux** [comment]
that makes two of us.



________________________________

**Comment by jordanpapaleo** [comment]
Read this for more info about our terminals https://github.com/CodeTahoe/CT100/blob/master/lessons/environment_setup.md#using-your-terminal-or-command-line
