### ISSUE TITLE
Sharing cool stuff

### ISSUE THREAD

**Issue by jordanpapaleo** [CodeTahoe/CT100#4]

**Comment by lhurt51** [comment]
I found a cool app that is for Android and IPhone called learn html also there is one for Java Script and CSS.

**Comment by drdelux** [comment]
thanks where do I find it?


________________________________

**Comment by lhurt51** [comment]
It would be in the app or android store. The company's name is Sololearn Inc and it is free.

**Comment by jordanpapaleo** [comment]
For those that are interested [Free Git Video Class](https://www.udemy.com/short-and-sweet-get-started-with-git-and-github-right-now/)

**Comment by Zenprechaun** [comment]
I was able to add some content to a page through a css rule where in the footer "Authored by: " is added before the author;

footer::before {
  content: "Authored by: "
}
