### ISSUE TITLE
Sending our finished code from the assigned Exercise

### ISSUE THREAD

**Issue by blazehalderman** [CodeTahoe/CT100#5]
Wondering where to send my code now that its on Github.com, do I send it via email?

**Comment by jordanpapaleo** [comment]
I just took a look and it looks good.  I love that you are exploring and doing more that the minimum but be careful what tags you use and make sure you look them up ;)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font

**Comment by blazehalderman** [comment]
Hi,


Thanks! So is font like "a dead element".  I was reading and it says that
people don't normally use it. What other element could I use instead of
font?

Blaze

On Thu, Mar 31, 2016 at 2:30 PM, Jordan Papaleo <notifications@github.com>
wrote:

> I just took a look and it looks good. I love that you are exploring and
> doing more that the minimum but be careful what tags you use and make sure
> you look them up ;)
>
> https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeTahoe/CT100/issues/5#issuecomment-204136856>
>



-- 
Blaze

**Comment by theaaronmartin** [comment]
I would wait until we touch on CSS to worry about changing the font. Jordan
might have a different opinion though.

**Comment by blazehalderman** [comment]
Gotcha. Just read that on the page he sent :)

On Thu, Mar 31, 2016 at 2:48 PM, Aaron Martin <notifications@github.com>
wrote:

> I would wait until we touch on CSS to worry about changing the font. Jordan
> might have a different opinion though.
> On Mar 31, 2016 2:46 PM, "blazehalderman" <notifications@github.com>
> wrote:
>
> > Hi,
> >
> >
> > Thanks! So is font like "a dead element". I was reading and it says that
> > people don't normally use it. What other element could I use instead of
> > font?
> >
> > Blaze
> >
> > On Thu, Mar 31, 2016 at 2:30 PM, Jordan Papaleo <
> notifications@github.com>
> > wrote:
> >
> > > I just took a look and it looks good. I love that you are exploring and
> > > doing more that the minimum but be careful what tags you use and make
> > sure
> > > you look them up ;)
> > >
> > > https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font
> > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/CodeTahoe/CT100/issues/5#issuecomment-204136856>
> > >
> >
> >
> >
> > --
> > Blaze
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/CodeTahoe/CT100/issues/5#issuecomment-204145024>
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CodeTahoe/CT100/issues/5#issuecomment-204145631>
>



-- 
Blaze

**Comment by blazehalderman** [comment]
Says it's better to use CSS

On Thu, Mar 31, 2016 at 2:48 PM, Blaze Halderman <blazerboy123@gmail.com>
wrote:

> Gotcha. Just read that on the page he sent :)
>
> On Thu, Mar 31, 2016 at 2:48 PM, Aaron Martin <notifications@github.com>
> wrote:
>
>> I would wait until we touch on CSS to worry about changing the font.
>> Jordan
>> might have a different opinion though.
>> On Mar 31, 2016 2:46 PM, "blazehalderman" <notifications@github.com>
>> wrote:
>>
>> > Hi,
>> >
>> >
>> > Thanks! So is font like "a dead element". I was reading and it says that
>> > people don't normally use it. What other element could I use instead of
>> > font?
>> >
>> > Blaze
>> >
>> > On Thu, Mar 31, 2016 at 2:30 PM, Jordan Papaleo <
>> notifications@github.com>
>> > wrote:
>> >
>> > > I just took a look and it looks good. I love that you are exploring
>> and
>> > > doing more that the minimum but be careful what tags you use and make
>> > sure
>> > > you look them up ;)
>> > >
>> > > https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font
>> > >
>> > > —
>> > > You are receiving this because you authored the thread.
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/CodeTahoe/CT100/issues/5#issuecomment-204136856>
>> > >
>> >
>> >
>> >
>> > --
>> > Blaze
>> >
>> > —
>> > You are receiving this because you are subscribed to this thread.
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/CodeTahoe/CT100/issues/5#issuecomment-204145024>
>>
>> >
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/CodeTahoe/CT100/issues/5#issuecomment-204145631>
>>
>
>
>
> --
> Blaze
>



-- 
Blaze

**Comment by jordanpapaleo** [comment]
Exactly but right now I want you guys focusing on semantics of content.  We will play with color very soon.
