### ISSUE TITLE
Kepmaping.cson for Atom

### ISSUE THREAD

**Issue by blazehalderman** [CodeTahoe/CT100#6]
# Your keymap
#
# You can find more information about keymaps in these guides:
# * https://atom.io/docs/latest/using-atom-basic-customization#customizing-key-bindings
# * https://atom.io/docs/latest/behind-atom-keymaps-in-depth

'atom-text-editor':
  'ctrl-alt-/': 'block-comment:toggle'
  'shift-delete': 'editor:delete-line'
  'ctrl-shift-D': 'editor:duplicate-lines'
  'ctrl-shift-J': 'editor:join-lines'
'atom-workspace atom-text-editor:not([mini])':
  'ctrl-shift-down': 'editor:move-line-down'
  'ctrl-shift-up': 'editor:move-line-up'

**Comment by blazehalderman** [comment]
copy and paste if < control >,</> does not work.

**Comment by blazehalderman** [comment]
only is for windows, don't have keymaps for mac.

**Comment by jordanpapaleo** [comment]
Thanks Blaze
