### ISSUE TITLE
Can we put forms in lists or list items? 

### ISSUE THREAD

**Issue by Zenprechaun** [CodeTahoe/CT100#7]

**Comment by jordanpapaleo** [comment]
Sure. But I am not sure why you would.  A list usually groups like items.    Why would you have a list of forms?

**Comment by Zenprechaun** [comment]
Because the registation form is in two sections. 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by jordanpapaleo** [comment]
Use a field set 

Sent from my iPhone

On Apr 7, 2016, at 11:53 PM, Michael McDermott <notifications@github.com> wrote:



Because the registation form is in two sections. 


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
